//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDuLich2Entities : DbContext
    {
        public QuanLyDuLich2Entities()
            : base("name=QuanLyDuLich2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbBaoCao> tbBaoCaos { get; set; }
        public DbSet<tbChiTietPhieuDichVu> tbChiTietPhieuDichVus { get; set; }
        public DbSet<tbDichVu> tbDichVus { get; set; }
        public DbSet<tbHoaDon> tbHoaDons { get; set; }
        public DbSet<tbKhach> tbKhaches { get; set; }
        public DbSet<tbLoaiPhong> tbLoaiPhongs { get; set; }
        public DbSet<tbLoaiSuCo> tbLoaiSuCoes { get; set; }
        public DbSet<tbLoaiTaiKhoan> tbLoaiTaiKhoans { get; set; }
        public DbSet<tbPhieuChuyenKhoan> tbPhieuChuyenKhoans { get; set; }
        public DbSet<tbPhieuDichVu> tbPhieuDichVus { get; set; }
        public DbSet<tbPhieuThuePhong> tbPhieuThuePhongs { get; set; }
        public DbSet<tbPhong> tbPhongs { get; set; }
        public DbSet<tbSuCo> tbSuCoes { get; set; }
        public DbSet<tbTaiKhoan> tbTaiKhoans { get; set; }
        public DbSet<tbTyGia> tbTyGias { get; set; }
    }
}
