//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBaoCao
    {
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public Nullable<double> DoanhThuTong { get; set; }
        public Nullable<int> KhachDen { get; set; }
        public Nullable<int> KhachDi { get; set; }
    }
}
