//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChiTietPhieuDichVu
    {
        public int PhieuDichVu { get; set; }
        public int DichVu { get; set; }
        public string YeuCauKhach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual tbDichVu tbDichVu { get; set; }
        public virtual tbPhieuDichVu tbPhieuDichVu { get; set; }
    }
}
