//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDichVu
    {
        public tbDichVu()
        {
            this.tbChiTietPhieuDichVus = new HashSet<tbChiTietPhieuDichVu>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual ICollection<tbChiTietPhieuDichVu> tbChiTietPhieuDichVus { get; set; }
    }
}
