//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKhach
    {
        public tbKhach()
        {
            this.tbHoaDons = new HashSet<tbHoaDon>();
            this.tbPhieuDichVus = new HashSet<tbPhieuDichVu>();
            this.tbPhieuThuePhongs = new HashSet<tbPhieuThuePhong>();
        }
    
        public int ID { get; set; }
        public string CMND { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<tbHoaDon> tbHoaDons { get; set; }
        public virtual ICollection<tbPhieuDichVu> tbPhieuDichVus { get; set; }
        public virtual ICollection<tbPhieuThuePhong> tbPhieuThuePhongs { get; set; }
    }
}
