//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoaiTaiKhoan
    {
        public tbLoaiTaiKhoan()
        {
            this.tbTaiKhoans = new HashSet<tbTaiKhoan>();
        }
    
        public string LoaiTaiKhoan { get; set; }
    
        public virtual ICollection<tbTaiKhoan> tbTaiKhoans { get; set; }
    }
}
