//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoaiPhong
    {
        public tbLoaiPhong()
        {
            this.tbPhongs = new HashSet<tbPhong>();
        }
    
        public string LoaiPhong { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<double> DonGiaThang { get; set; }
        public Nullable<double> DonGiaNgay { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<tbPhong> tbPhongs { get; set; }
    }
}
