//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoaiSuCo
    {
        public tbLoaiSuCo()
        {
            this.tbSuCoes = new HashSet<tbSuCo>();
        }
    
        public string LoaiSuCo { get; set; }
    
        public virtual ICollection<tbSuCo> tbSuCoes { get; set; }
    }
}
