//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhieuDichVu()
        {
            this.tbChiTietPhieuDichVus = new HashSet<tbChiTietPhieuDichVu>();
        }
    
        public int ID { get; set; }
        public int Khach { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<double> TienGiam { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public int HoaDon { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChiTietPhieuDichVu> tbChiTietPhieuDichVus { get; set; }
        public virtual tbHoaDon tbHoaDon { get; set; }
        public virtual tbKhach tbKhach { get; set; }
    }
}
