//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuChuyenKhoan
    {
        public tbPhieuChuyenKhoan()
        {
            this.tbHoaDons = new HashSet<tbHoaDon>();
        }
    
        public int ID { get; set; }
        public double SoTien { get; set; }
        public string NoiDung { get; set; }
        public string NgoaiTe { get; set; }
        public string SoTaiKhoan { get; set; }
    
        public virtual ICollection<tbHoaDon> tbHoaDons { get; set; }
        public virtual tbTyGia tbTyGia { get; set; }
    }
}
