//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhong
    {
        public tbPhong()
        {
            this.tbPhieuThuePhongs = new HashSet<tbPhieuThuePhong>();
        }
    
        public string SoPhong { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual tbLoaiPhong tbLoaiPhong { get; set; }
        public virtual ICollection<tbPhieuThuePhong> tbPhieuThuePhongs { get; set; }
    }
}
