//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTyGia
    {
        public tbTyGia()
        {
            this.tbPhieuChuyenKhoans = new HashSet<tbPhieuChuyenKhoan>();
        }
    
        public string NgoaiTe { get; set; }
        public Nullable<double> TyGia { get; set; }
    
        public virtual ICollection<tbPhieuChuyenKhoan> tbPhieuChuyenKhoans { get; set; }
    }
}
